### ISSUE TITLE
studiesStudyDbIdObservationvariablesGetAsync()

### ISSUE THREAD

**Issue by peterrosario** [plantbreeding/API#377]
When I call the Java client's `StudiesApi.studiesStudyDbIdObservationvariablesGetAsync()` with studyDbId == 1001 I get:
```
    java.lang.IllegalArgumentException: missing discriminator field: <>
        at io.swagger.client.JSON.getDiscriminatorValue(JSON.java:83)
        at io.swagger.client.JSON.access$000(JSON.java:41)
        at io.swagger.client.JSON$2.getClassForElement(JSON.java:61)
        at io.gsonfire.gson.TypeSelectorTypeAdapterFactory$TypeSelectorTypeAdapter.read(TypeSelectorTypeAdapterFactory.java:65)
        at io.gsonfire.gson.NullableTypeAdapter.read(NullableTypeAdapter.java:36)
        at io.gsonfire.gson.HooksTypeAdapter.deserialize(HooksTypeAdapter.java:86)
        at io.gsonfire.gson.HooksTypeAdapter.read(HooksTypeAdapter.java:54)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
        at com.google.gson.Gson.fromJson(Gson.java:927)
        at com.google.gson.Gson.fromJson(Gson.java:892)
        at com.google.gson.Gson.fromJson(Gson.java:841)
        at io.swagger.client.JSON.deserialize(JSON.java:157)
        at io.swagger.client.ApiClient.deserialize(ApiClient.java:710)
        at io.swagger.client.ApiClient.handleResponse(ApiClient.java:913)
        at io.swagger.client.ApiClient$1.onResponse(ApiClient.java:879)
        at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
        at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
```

**Comment by BrapiCoordinatorSelby** [comment]
I have found an acceptable solution to this problem in the Java client code generated from BrAPI V2.0. 
The generated code contains a class `JSON.java` which handles the JSON serialization and de-serialization of the JSON objects. The problem is when it is de-serializing an object, it is expecting an extra "discriminator" field to handle Java type resolution. If this class had been responsible for the original serialization, then this would not be a problem, however since the JSON is coming from a remote server, the "discriminator" field is missing, just as the error message indicates. 

The easiest solution is to modify `JSON.java` and tell it how to determine the correct class without the need for an independant discriminator field. For example, `Study.java` has an extra field `studyDbId` and `StudyNewRequest.java` does not have this field. Based on the presence or absence of `studyDbId` in the response JSON, I can determine which class to instantiate. 

@peterrosario if and when you are ready to move to V2.0 for your java client, let me know and I can give you my code changes for `JSON.java`
